on: deployment_status
name: a11y-scanning
jobs:
  build:
    name: a11y
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: a11y check
      uses: docker://cdssnc/a11y-multiple-page-checker
