name: dts-publish-deploy

on: 
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      uses: einaregilsson/build-number@v1 
      with:
        token: ${{secrets.github_token}}        
    - name: Print new build number
      run: echo Build number is $BUILD_NUMBER   
    - uses: azure/docker-login@v1
      with:
        login-server: mtscontainers.azurecr.io
        username: ${{ secrets.DTS_AZURE_USERNAME }}
        password: ${{ secrets.DTS_AZURE_PASSWORD }}
    - uses: actions/checkout@v1
    - name: docker build and push
      run: |
        docker build -t mtscontainers.azurecr.io/dts-scheduler:latest .
        docker tag mtscontainers.azurecr.io/dts-scheduler:latest mtscontainers.azurecr.io/dts-scheduler:$BUILD_NUMBER
        docker push mtscontainers.azurecr.io/dts-scheduler:latest
        docker push mtscontainers.azurecr.io/dts-scheduler:$BUILD_NUMBER

  Deploy:
    name: Deploy
    needs: publish
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jenkins.esdc.online/job/dts-scheduler/buildWithParameters?token=${{ secrets.DTS_JENKINS_BUILD_TOKEN }}&docker_tag=latest"
        user: "jenkinsbot"
        token: ${{ secrets.DTS_JENKINS_TOKEN }}
        job: "dts-scheduler"


