name: Publish_Artifact

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure WebApp Container
      uses: Azure/webapps-container-deploy@v1


